/**
 * The quiz's catalogue and questions, carried across from the old project.
 *
 * `src/quiz/GovtJobQuiz.jsx` in the Vite app — fifty exams with their
 * eligibility, sectors, salary bands and difficulty, and the ten questions that
 * interrogate them. Copied rather than rewritten: this is a hand-curated
 * dataset about real recruitment, and every number in it (an age ceiling, a pay
 * band) is a fact somebody checked against a notification. Retyping it from
 * memory would silently invent facts.
 *
 * What changed is the container, not the content: TypeScript types so the
 * scorer cannot read a field that does not exist, and `as const` on the
 * education ladder so its order is part of the type.
 *
 * The data is deliberately separate from `score.ts`, which is pure and tested,
 * and from the page, which renders it. The old file was 1,358 lines with all
 * three in it.
 *
 * Separate from `questions.ts` for a measured reason, not a tidy one. This
 * module is ~30 kB of catalogue and the quiz's opening screen does not need a
 * byte of it — so the runner imports the questions statically and reaches for
 * this one, through `score.ts`, only when it has ten answers to score. Kept
 * together, /quiz was 163.8 kB against a 161 kB budget; split, the catalogue
 * downloads while the first question is on screen and is never fetched at all
 * by somebody who opens the page and leaves.
 */

export type EducationLevel = (typeof EDUCATION_ORDER)[number];

export type Difficulty = "easy" | "medium" | "hard";

export interface QuizExam {
  id: string;
  name: string;
  body: string;
  tag: string;
  minEducation: string;
  minAge: number;
  /** Per reservation category. `general` is the fallback for anything absent. */
  maxAge: Record<string, number>;
  /** Empty means "no state restriction" — a central exam. */
  states: string[];
  sectors: string[];
  interests: string[];
  /** [floor, ceiling] of the pay band, in rupees per month. */
  salaryRange: [number, number];
  difficulty: Difficulty;
  languages: string[];
  desc: string;
  educationTags: string[];
}

/** The education ladder, low to high. Index order is the comparison. */
export const EDUCATION_ORDER = [
  "10th",
  "12th",
  "diploma",
  "btech",
  "bsc",
  "ba",
  "bcom",
  "llb",
  "graduate",
  "pg",
] as const;

export const EXAMS: QuizExam[] = [
  // ── UPSC ──
  {
    id: "upsc-cse",
    name: "UPSC Civil Services",
    body: "UPSC",
    tag: "IAS / IPS / IFS",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 32, obc: 35, sc: 37, st: 37, ews: 32 },
    states: [],
    sectors: ["administration", "police", "foreign"],
    interests: ["gk", "polity", "history", "geography"],
    salaryRange: [56100, 250000],
    difficulty: "hard",
    languages: ["english", "hindi"],
    desc: "India's most prestigious exam. Entry to IAS, IPS, IFS and 22 other services.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "upsc-capf",
    name: "UPSC CAPF",
    body: "UPSC",
    tag: "Assistant Commandant",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 25, obc: 28, sc: 30, st: 30, ews: 25 },
    states: [],
    sectors: ["police", "defence", "paramilitary"],
    interests: ["gk", "polity", "physical"],
    salaryRange: [56100, 177500],
    difficulty: "hard",
    languages: ["english", "hindi"],
    desc: "Officer rank in BSF, CRPF, CISF, ITBP, SSB paramilitary forces.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "upsc-ese",
    name: "UPSC ESE / IES",
    body: "UPSC",
    tag: "Engineering Services",
    minEducation: "btech",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["engineering", "technical", "administration"],
    interests: ["science", "maths", "technical"],
    salaryRange: [56100, 177500],
    difficulty: "hard",
    languages: ["english"],
    desc: "Engineer officers in railways, telecom, defence, CPWD. Engineering graduates only.",
    educationTags: ["B.Tech / B.E"],
  },

  {
    id: "nda",
    name: "NDA / NA",
    body: "UPSC",
    tag: "Defence Officer",
    minEducation: "12th",
    minAge: 16.5,
    maxAge: { general: 19.5, obc: 19.5, sc: 19.5, st: 19.5, ews: 19.5 },
    states: [],
    sectors: ["defence", "army", "navy", "airforce"],
    interests: ["maths", "gk", "physical", "science"],
    salaryRange: [56100, 177500],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Entry to Army, Navy, Air Force as officer. Only for 12th pass students.",
    educationTags: ["12th Pass"],
  },

  {
    id: "cds",
    name: "CDS",
    body: "UPSC",
    tag: "Combined Defence Services",
    minEducation: "graduate",
    minAge: 19,
    maxAge: { general: 25, obc: 25, sc: 25, st: 25, ews: 25 },
    states: [],
    sectors: ["defence", "army", "navy", "airforce"],
    interests: ["gk", "english", "maths", "physical"],
    salaryRange: [56100, 177500],
    difficulty: "medium",
    languages: ["english"],
    desc: "Officer entry into Army, Navy, Air Force for graduates.",
    educationTags: ["Any Graduate"],
  },

  // ── SSC ──
  {
    id: "ssc-cgl",
    name: "SSC CGL",
    body: "SSC",
    tag: "Group B & C Central Govt",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 27, obc: 30, sc: 32, st: 32, ews: 27 },
    states: [],
    sectors: ["administration", "tax", "audit", "statistics"],
    interests: ["maths", "reasoning", "english", "gk"],
    salaryRange: [25500, 81100],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Most popular central govt exam. Thousands of posts across all ministries.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "ssc-chsl",
    name: "SSC CHSL",
    body: "SSC",
    tag: "10+2 Level Posts",
    minEducation: "12th",
    minAge: 18,
    maxAge: { general: 27, obc: 30, sc: 32, st: 32, ews: 27 },
    states: [],
    sectors: ["administration", "postal"],
    interests: ["maths", "reasoning", "english", "gk"],
    salaryRange: [19900, 34800],
    difficulty: "easy",
    languages: ["english", "hindi"],
    desc: "LDC, JSA, PA, SA posts in central govt departments and ministries.",
    educationTags: ["12th Pass"],
  },

  {
    id: "ssc-mts",
    name: "SSC MTS",
    body: "SSC",
    tag: "Multi Tasking Staff",
    minEducation: "10th",
    minAge: 18,
    maxAge: { general: 25, obc: 28, sc: 30, st: 30, ews: 25 },
    states: [],
    sectors: ["administration"],
    interests: ["reasoning", "gk"],
    salaryRange: [18000, 22000],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Entry-level central govt posts. Only 10th pass required. Huge vacancies every year.",
    educationTags: ["10th Pass"],
  },

  {
    id: "ssc-cpo",
    name: "SSC CPO",
    body: "SSC",
    tag: "Central Police Organisations",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 25, obc: 28, sc: 30, st: 30, ews: 25 },
    states: [],
    sectors: ["police", "paramilitary"],
    interests: ["gk", "reasoning", "physical", "english"],
    salaryRange: [35400, 112400],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Sub-Inspector in Delhi Police, BSF, CRPF, CISF, SSB, ITBP.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "ssc-gd",
    name: "SSC GD Constable",
    body: "SSC",
    tag: "General Duty Constable",
    minEducation: "10th",
    minAge: 18,
    maxAge: { general: 23, obc: 26, sc: 28, st: 28, ews: 23 },
    states: [],
    sectors: ["police", "paramilitary"],
    interests: ["physical", "gk", "reasoning"],
    salaryRange: [21700, 69100],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Constable in BSF, CRPF, CISF, SSB, ITBP, NIA. Largest vacancies in India.",
    educationTags: ["10th Pass"],
  },

  {
    id: "ssc-je",
    name: "SSC JE",
    body: "SSC",
    tag: "Junior Engineer",
    minEducation: "diploma",
    minAge: 18,
    maxAge: { general: 32, obc: 35, sc: 37, st: 37, ews: 32 },
    states: [],
    sectors: ["engineering", "technical"],
    interests: ["science", "maths", "technical"],
    salaryRange: [35400, 112400],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Junior Engineer in CPWD, MES, CWC. Diploma or degree in engineering required.",
    educationTags: ["Diploma / B.Tech"],
  },

  // ── Railways ──
  {
    id: "rrb-ntpc",
    name: "RRB NTPC",
    body: "Railway Recruitment Board",
    tag: "Non-Technical Popular Categories",
    minEducation: "12th",
    minAge: 18,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["railways", "administration"],
    interests: ["maths", "reasoning", "gk"],
    salaryRange: [19900, 35400],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Massive railway recruitment. Clerk, Goods Guard, ASM and more posts.",
    educationTags: ["12th / Graduate"],
  },

  {
    id: "rrb-group-d",
    name: "RRB Group D",
    body: "Railway Recruitment Board",
    tag: "Level 1 Railways",
    minEducation: "10th",
    minAge: 18,
    maxAge: { general: 33, obc: 36, sc: 38, st: 38, ews: 33 },
    states: [],
    sectors: ["railways"],
    interests: ["maths", "reasoning", "gk", "science"],
    salaryRange: [18000, 56900],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Track maintainer, helper, porter and other Level 1 railway posts.",
    educationTags: ["10th Pass"],
  },

  {
    id: "rrb-je",
    name: "RRB JE",
    body: "Railway Recruitment Board",
    tag: "Junior Engineer Railways",
    minEducation: "diploma",
    minAge: 18,
    maxAge: { general: 33, obc: 36, sc: 38, st: 38, ews: 33 },
    states: [],
    sectors: ["railways", "engineering", "technical"],
    interests: ["science", "maths", "technical"],
    salaryRange: [35400, 112400],
    difficulty: "medium",
    languages: ["english", "hindi", "regional"],
    desc: "Junior Engineer and Depot Material Superintendent in Indian Railways.",
    educationTags: ["Diploma / B.Tech"],
  },

  {
    id: "rrb-alp",
    name: "RRB ALP",
    body: "Railway Recruitment Board",
    tag: "Assistant Loco Pilot",
    minEducation: "10th",
    minAge: 18,
    maxAge: { general: 28, obc: 31, sc: 33, st: 33, ews: 28 },
    states: [],
    sectors: ["railways", "technical"],
    interests: ["science", "maths", "technical"],
    salaryRange: [19900, 62000],
    difficulty: "medium",
    languages: ["english", "hindi", "regional"],
    desc: "Train driver cadre. ITI or diploma in relevant trade required.",
    educationTags: ["10th + ITI / Diploma"],
  },

  // ── Banking ──
  {
    id: "rbi-grade-b",
    name: "RBI Grade B",
    body: "RBI",
    tag: "Officer Grade B",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["banking", "finance", "economics"],
    interests: ["maths", "reasoning", "english", "banking", "gk"],
    salaryRange: [55000, 96610],
    difficulty: "hard",
    languages: ["english"],
    desc: "Officer at Reserve Bank of India. One of the most coveted banking roles in India.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "sbi-po",
    name: "SBI PO",
    body: "SBI",
    tag: "Probationary Officer",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["banking", "finance"],
    interests: ["maths", "reasoning", "english", "banking"],
    salaryRange: [41960, 66070],
    difficulty: "hard",
    languages: ["english", "hindi"],
    desc: "Most coveted banking job. Officer in India's largest public sector bank.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "sbi-clerk",
    name: "SBI Clerk",
    body: "SBI",
    tag: "Junior Associates",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 28, obc: 31, sc: 33, st: 33, ews: 28 },
    states: [],
    sectors: ["banking"],
    interests: ["maths", "reasoning", "english"],
    salaryRange: [17900, 47920],
    difficulty: "medium",
    languages: ["english", "hindi", "regional"],
    desc: "Clerk posts in SBI branches across India. Local language proficiency required.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "ibps-po",
    name: "IBPS PO",
    body: "IBPS",
    tag: "Probationary Officer",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["banking", "finance"],
    interests: ["maths", "reasoning", "english", "banking"],
    salaryRange: [36000, 63840],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Officer-level posts in 12 public sector banks across India.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "ibps-clerk",
    name: "IBPS Clerk",
    body: "IBPS",
    tag: "Bank Clerk",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 28, obc: 31, sc: 33, st: 33, ews: 28 },
    states: [],
    sectors: ["banking"],
    interests: ["maths", "reasoning", "english", "banking"],
    salaryRange: [11765, 42020],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Entry-level banking jobs in 12 public sector banks. High job security.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "ibps-rrb-po",
    name: "IBPS RRB Officer",
    body: "IBPS",
    tag: "Regional Rural Bank PO",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: ["home_state"],
    sectors: ["banking", "rural"],
    interests: ["maths", "reasoning", "regional", "banking"],
    salaryRange: [29000, 52000],
    difficulty: "medium",
    languages: ["hindi", "regional"],
    desc: "Officer in Regional Rural Banks. Strong preference for home state candidates.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "nabard-grade-a",
    name: "NABARD Grade A",
    body: "NABARD",
    tag: "Assistant Manager",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["banking", "finance", "rural", "agriculture"],
    interests: ["maths", "reasoning", "english", "banking", "gk"],
    salaryRange: [44500, 89150],
    difficulty: "hard",
    languages: ["english", "hindi"],
    desc: "Assistant Manager in NABARD. Focus on agriculture and rural development finance.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "sebi-grade-a",
    name: "SEBI Grade A",
    body: "SEBI",
    tag: "Officer Grade A",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["finance", "banking", "law"],
    interests: ["maths", "reasoning", "english", "banking", "gk", "law"],
    salaryRange: [44500, 89150],
    difficulty: "hard",
    languages: ["english"],
    desc: "Officer at Securities and Exchange Board of India. Finance/law/CA background preferred.",
    educationTags: ["Any Graduate / LLB / CA"],
  },

  {
    id: "lic-aao",
    name: "LIC AAO",
    body: "LIC",
    tag: "Assistant Administrative Officer",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["insurance", "finance"],
    interests: ["maths", "reasoning", "english", "banking"],
    salaryRange: [32795, 62315],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Officer cadre in Life Insurance Corporation of India.",
    educationTags: ["Any Graduate"],
  },

  // ── Law ──
  {
    id: "apo",
    name: "APO / District Judge",
    body: "State PSC / High Court",
    tag: "Law Officer",
    minEducation: "llb",
    minAge: 21,
    maxAge: { general: 35, obc: 38, sc: 40, st: 40, ews: 35 },
    states: ["home_state"],
    sectors: ["law", "administration", "judiciary"],
    interests: ["law", "polity", "english", "gk"],
    salaryRange: [27700, 144300],
    difficulty: "hard",
    languages: ["english", "hindi", "regional"],
    desc: "Assistant Prosecution Officer or District Judge via state judiciary exams. LLB required.",
    educationTags: ["LLB / LLM"],
  },

  {
    id: "upsc-law-officer",
    name: "UPSC Law Officer",
    body: "UPSC",
    tag: "Legal Officer Central Govt",
    minEducation: "llb",
    minAge: 21,
    maxAge: { general: 35, obc: 38, sc: 40, st: 40, ews: 35 },
    states: [],
    sectors: ["law", "administration"],
    interests: ["law", "polity", "english"],
    salaryRange: [44900, 142400],
    difficulty: "hard",
    languages: ["english"],
    desc: "Legal Officer posts in central government ministries and departments via UPSC.",
    educationTags: ["LLB / LLM"],
  },

  // ── State PSC ──
  {
    id: "state-psc",
    name: "State PSC (PCS)",
    body: "State PSC",
    tag: "State Group A & B",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 35, obc: 38, sc: 40, st: 40, ews: 35 },
    states: ["home_state"],
    sectors: ["administration", "police", "revenue"],
    interests: ["gk", "history", "polity", "regional"],
    salaryRange: [35400, 112400],
    difficulty: "hard",
    languages: ["english", "hindi", "regional"],
    desc: "State-level administrative services (SDM, DSP, BDO). Higher age limit, regional posting.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "state-si",
    name: "State Police SI",
    body: "State Police",
    tag: "Sub Inspector",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 25, obc: 28, sc: 30, st: 30, ews: 25 },
    states: ["home_state"],
    sectors: ["police"],
    interests: ["gk", "reasoning", "physical", "polity"],
    salaryRange: [20000, 60000],
    difficulty: "medium",
    languages: ["hindi", "regional"],
    desc: "Sub Inspector in state police. Physical test mandatory. State-specific exam.",
    educationTags: ["Any Graduate"],
  },

  // ── Teaching ──
  {
    id: "ctet",
    name: "CTET",
    body: "CBSE",
    tag: "Central Teacher Eligibility Test",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 99, obc: 99, sc: 99, st: 99, ews: 99 },
    states: [],
    sectors: ["teaching", "education"],
    interests: ["english", "reasoning", "gk", "regional"],
    salaryRange: [35400, 80000],
    difficulty: "easy",
    languages: ["english", "hindi"],
    desc: "Eligibility certificate for central govt school teacher (Class 1–8). No upper age limit.",
    educationTags: ["B.Ed / D.El.Ed"],
  },

  {
    id: "kvs-tgt-pgt",
    name: "KVS TGT / PGT",
    body: "KVS",
    tag: "Kendriya Vidyalaya Teacher",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 35, obc: 38, sc: 40, st: 40, ews: 35 },
    states: [],
    sectors: ["teaching", "education"],
    interests: ["english", "gk", "regional", "science"],
    salaryRange: [44900, 112400],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Teacher posts in Kendriya Vidyalayas across India. CTET qualification required.",
    educationTags: ["Graduate + B.Ed"],
  },

  // ── Technical / Science ──
  {
    id: "isro-scientist",
    name: "ISRO Scientist / Engineer",
    body: "ISRO",
    tag: "Scientist SC",
    minEducation: "btech",
    minAge: 18,
    maxAge: { general: 35, obc: 38, sc: 40, st: 40, ews: 35 },
    states: [],
    sectors: ["engineering", "technical", "science"],
    interests: ["science", "maths", "technical"],
    salaryRange: [56100, 177500],
    difficulty: "hard",
    languages: ["english"],
    desc: "Scientist or Engineer in India's space agency ISRO. B.Tech in relevant discipline required.",
    educationTags: ["B.Tech / B.E"],
  },

  {
    id: "drdo-ceptam",
    name: "DRDO CEPTAM",
    body: "DRDO",
    tag: "Technician / Admin",
    minEducation: "10th",
    minAge: 18,
    maxAge: { general: 28, obc: 31, sc: 33, st: 33, ews: 28 },
    states: [],
    sectors: ["technical", "defence", "engineering"],
    interests: ["science", "maths", "technical", "reasoning"],
    salaryRange: [25500, 81100],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Technician and admin posts in Defence R&D labs. Various education levels accepted.",
    educationTags: ["10th / ITI / Diploma / Graduate"],
  },

  {
    id: "aai-atc",
    name: "AAI Junior Executive (ATC)",
    body: "Airports Authority of India",
    tag: "Air Traffic Control",
    minEducation: "btech",
    minAge: 18,
    maxAge: { general: 27, obc: 30, sc: 32, st: 32, ews: 27 },
    states: [],
    sectors: ["engineering", "technical", "science"],
    interests: ["science", "maths", "technical", "english"],
    salaryRange: [40000, 140000],
    difficulty: "hard",
    languages: ["english"],
    desc: "Air Traffic Controller cadre at AAI. B.Sc (PCM) or B.E/B.Tech with valid academic level required.",
    educationTags: ["B.Sc (PCM) / B.E / B.Tech"],
  },

  // ── More Banking & Insurance ──
  {
    id: "rbi-assistant",
    name: "RBI Assistant",
    body: "RBI",
    tag: "Clerical / Support Staff",
    minEducation: "graduate",
    minAge: 20,
    maxAge: { general: 28, obc: 31, sc: 33, st: 33, ews: 28 },
    states: [],
    sectors: ["banking", "finance"],
    interests: ["maths", "reasoning", "english", "banking", "gk"],
    salaryRange: [20700, 40000],
    difficulty: "medium",
    languages: ["english", "hindi", "regional"],
    desc: "Support-staff cadre at the Reserve Bank of India. Great pay and prestige for a clerical role.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "ibps-rrb-clerk",
    name: "IBPS RRB Office Assistant",
    body: "IBPS",
    tag: "Regional Rural Bank Clerk",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 28, obc: 31, sc: 33, st: 33, ews: 28 },
    states: ["home_state"],
    sectors: ["banking", "rural"],
    interests: ["maths", "reasoning", "regional", "banking"],
    salaryRange: [15000, 40000],
    difficulty: "easy",
    languages: ["hindi", "regional"],
    desc: "Clerk (Office Assistant) in Regional Rural Banks. Strong home-state and local-language preference.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "niacl-ao",
    name: "NIACL AO",
    body: "New India Assurance",
    tag: "Administrative Officer",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["insurance", "finance"],
    interests: ["maths", "reasoning", "english", "banking", "gk"],
    salaryRange: [50000, 90000],
    difficulty: "medium",
    languages: ["english"],
    desc: "Officer cadre in New India Assurance, India's largest general insurance company.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "lic-ado",
    name: "LIC ADO",
    body: "LIC",
    tag: "Apprentice Development Officer",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["insurance", "finance"],
    interests: ["english", "reasoning", "gk"],
    salaryRange: [35000, 55000],
    difficulty: "medium",
    languages: ["english", "hindi", "regional"],
    desc: "Field-officer cadre at LIC focused on building and managing the agency network.",
    educationTags: ["Any Graduate"],
  },

  // ── More SSC & Central Staffing ──
  {
    id: "ssc-steno",
    name: "SSC Stenographer",
    body: "SSC",
    tag: "Steno Grade C & D",
    minEducation: "12th",
    minAge: 18,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["administration"],
    interests: ["english", "reasoning", "gk"],
    salaryRange: [25500, 81100],
    difficulty: "easy",
    languages: ["english", "hindi"],
    desc: "Stenographer posts across central government ministries. Shorthand skill test required.",
    educationTags: ["12th Pass"],
  },

  {
    id: "ssc-jht",
    name: "SSC Junior Hindi Translator",
    body: "SSC",
    tag: "Translator (JHT)",
    minEducation: "pg",
    minAge: 18,
    maxAge: { general: 30, obc: 33, sc: 35, st: 35, ews: 30 },
    states: [],
    sectors: ["administration", "teaching"],
    interests: ["english", "regional", "gk"],
    salaryRange: [35400, 112400],
    difficulty: "medium",
    languages: ["hindi", "english"],
    desc: "Hindi/English translator posts in central departments. Master's in Hindi or English required.",
    educationTags: ["Master's (Hindi / English)"],
  },

  {
    id: "ib-acio",
    name: "IB ACIO Grade-II",
    body: "Intelligence Bureau (MHA)",
    tag: "Intelligence Officer",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 27, obc: 30, sc: 32, st: 32, ews: 27 },
    states: [],
    sectors: ["administration", "police"],
    interests: ["gk", "reasoning", "english", "polity"],
    salaryRange: [44900, 142400],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Assistant Central Intelligence Officer in India's internal intelligence agency.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "epfo-ssa",
    name: "EPFO SSA",
    body: "EPFO",
    tag: "Social Security Assistant",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 27, obc: 30, sc: 32, st: 32, ews: 27 },
    states: [],
    sectors: ["administration", "finance"],
    interests: ["maths", "reasoning", "english", "gk"],
    salaryRange: [29200, 92300],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Social Security Assistant managing PF accounts and claims at the EPFO.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "fci-ag3",
    name: "FCI Assistant Grade-III",
    body: "Food Corporation of India",
    tag: "Assistant Grade III",
    minEducation: "graduate",
    minAge: 18,
    maxAge: { general: 27, obc: 30, sc: 32, st: 32, ews: 27 },
    states: [],
    sectors: ["administration", "rural"],
    interests: ["maths", "reasoning", "english", "gk"],
    salaryRange: [25380, 46220],
    difficulty: "easy",
    languages: ["english", "hindi"],
    desc: "General, technical and depot posts in the Food Corporation of India. Good work-life balance.",
    educationTags: ["Any Graduate"],
  },

  {
    id: "post-gds",
    name: "India Post GDS",
    body: "India Post",
    tag: "Gramin Dak Sevak",
    minEducation: "10th",
    minAge: 18,
    maxAge: { general: 40, obc: 43, sc: 45, st: 45, ews: 40 },
    states: ["home_state"],
    sectors: ["administration"],
    interests: ["regional", "reasoning"],
    salaryRange: [10000, 24470],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Branch Postmaster and Dak Sevak posts. Merit-based (no exam), 10th pass, huge vacancies.",
    educationTags: ["10th Pass"],
  },

  // ── Teaching & Research ──
  {
    id: "ugc-net",
    name: "UGC NET",
    body: "NTA / UGC",
    tag: "Assistant Professor & JRF",
    minEducation: "pg",
    minAge: 18,
    maxAge: { general: 99, obc: 99, sc: 99, st: 99, ews: 99 },
    states: [],
    sectors: ["teaching", "education"],
    interests: ["english", "gk", "reasoning", "polity"],
    salaryRange: [57700, 182400],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Eligibility for Assistant Professor and JRF in universities and colleges. Post-graduation required.",
    educationTags: ["Post Graduate (55%)"],
  },

  {
    id: "csir-net",
    name: "CSIR UGC NET",
    body: "NTA / CSIR",
    tag: "Science Lectureship & JRF",
    minEducation: "pg",
    minAge: 18,
    maxAge: { general: 99, obc: 99, sc: 99, st: 99, ews: 99 },
    states: [],
    sectors: ["teaching", "education", "engineering"],
    interests: ["science", "maths", "technical"],
    salaryRange: [37000, 182400],
    difficulty: "hard",
    languages: ["english"],
    desc: "Lectureship and JRF in science streams (Physics, Chemistry, Life Sciences, Maths, Earth Sciences).",
    educationTags: ["M.Sc / equivalent"],
  },

  // ── Defence: Agnipath & Coast Guard ──
  {
    id: "upsc-ifos",
    name: "UPSC IFoS",
    body: "UPSC",
    tag: "Indian Forest Service",
    minEducation: "graduate",
    minAge: 21,
    maxAge: { general: 32, obc: 35, sc: 37, st: 37, ews: 32 },
    states: [],
    sectors: ["administration", "science"],
    interests: ["science", "gk", "geography", "maths"],
    salaryRange: [56100, 225000],
    difficulty: "hard",
    languages: ["english"],
    desc: "Forest Service officer managing India's forests and wildlife. Science or engineering graduates only.",
    educationTags: ["Science / Engineering Graduate"],
  },

  {
    id: "agniveer-army",
    name: "Army Agniveer (GD)",
    body: "Indian Army",
    tag: "Agnipath General Duty",
    minEducation: "10th",
    minAge: 17.5,
    maxAge: { general: 21, obc: 21, sc: 21, st: 21, ews: 21 },
    states: [],
    sectors: ["defence", "army"],
    interests: ["physical", "gk", "reasoning"],
    salaryRange: [21000, 40000],
    difficulty: "easy",
    languages: ["english", "hindi", "regional"],
    desc: "Four-year Agniveer enrolment in the Indian Army. Physical fitness test and medical mandatory.",
    educationTags: ["10th Pass"],
  },

  {
    id: "agniveer-airforce",
    name: "IAF Agniveer Vayu",
    body: "Indian Air Force",
    tag: "Agnipath Vayu",
    minEducation: "12th",
    minAge: 17.5,
    maxAge: { general: 21, obc: 21, sc: 21, st: 21, ews: 21 },
    states: [],
    sectors: ["defence", "airforce"],
    interests: ["science", "maths", "physical"],
    salaryRange: [21000, 40000],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Four-year Agniveer enrolment in the Indian Air Force. 12th with PCM or vocational stream.",
    educationTags: ["12th (PCM / Vocational)"],
  },

  {
    id: "agniveer-navy",
    name: "Navy Agniveer (SSR)",
    body: "Indian Navy",
    tag: "Agnipath SSR",
    minEducation: "12th",
    minAge: 17.5,
    maxAge: { general: 21, obc: 21, sc: 21, st: 21, ews: 21 },
    states: [],
    sectors: ["defence", "navy"],
    interests: ["science", "maths", "physical"],
    salaryRange: [21000, 40000],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Four-year Agniveer enrolment in the Indian Navy (Senior Secondary Recruit). PCM in 12th required.",
    educationTags: ["12th (PCM)"],
  },

  {
    id: "coast-guard-navik",
    name: "Coast Guard Navik (GD)",
    body: "Indian Coast Guard",
    tag: "Navik General Duty",
    minEducation: "12th",
    minAge: 18,
    maxAge: { general: 22, obc: 22, sc: 22, st: 22, ews: 22 },
    states: [],
    sectors: ["defence", "navy"],
    interests: ["science", "maths", "physical"],
    salaryRange: [21700, 69100],
    difficulty: "medium",
    languages: ["english", "hindi"],
    desc: "Sailor entry into the Indian Coast Guard. 12th with Physics and Maths required.",
    educationTags: ["12th (PCM)"],
  },
];
